function AItext = image2Text(imageFile)

    %apiKey =
    %apiKey = 
    %apiUrl = 'https://openrouter.ai/api/v1/chat/completions';
    apiUrl = 'https://api.openai.com/v1/chat/completions';

    AItext = ' ';


    %이미지 base64 인코딩
    fid = fopen(imageFile, 'rb');
    imgData = fread(fid, '*uint8');
    fclose(fid);
    imgBase64 = matlab.net.base64encode(imgData);
    safeImageUrl = jsonencode(['data:image/jpeg;base64,' imgBase64]);


prompt = [
        '이 트러스 구조 이미지에서 각 노드의 상대 좌표를 식별해줘. ' ...
        '먼저 눈에 띄는 기준 노드(예: A, B, C, D, M 등)의 좌표를 먼저 정확히 식별하고, ' ...
        '좌표를 직접 추정하기 어려운 노드들은, 기존 노드들 간의 위치 관계를 고려해 ' ...
        'x좌표와 y좌표 모두에 대해 다음 방식으로 보간하여 추정해줘: ' ...
        '  → x좌표 = (x1 + x2)/2,  y좌표 = (y1 + y2)/2 ' ...
        '즉, 두 노드 사이에 위치한 노드일 경우 x뿐 아니라 y도 반드시 평균값으로 계산해줘. ' ...
        '예를 들어, (0,0)과 (4,3) 사이의 중간 노드는 (2,1.5)로 추정해야 해. ' ...
        '모든 노드 쌍 중 실제로 막대(member)로 연결된 것들을 빠짐없이 추출해줘. ' ...
        '이미지 상에서 선으로 연결된 노드들만 members로 포함시켜줘. ' ...
        '치수 표시를 위한 얇은 선(치수선), 글자, 눈금 등은 모두 무시하고, 오직 트러스 멤버로 보이는 선만 members에 포함시켜줘. ' ...
        '노드는 맨 왼쪽을 (0,0)으로 기준 잡고 상대 좌표로 정리하고, ' ...
        '"nodes = [x1 y1; x2 y2; ...]" 형식, ' ...
        'members는 "members = [i j; k l; ...]" 형식으로 출력해줘. ' ...
        '지점 조건(supports)은 supports 배열로 나타내줘. ' ...
        '   "pinned"은 0, "roller"는 1로 표시해서 supports = [type x y] 형식으로 출력해줘. ' ...
        '   예: supports = [0 0 0; 1 8 3]; ' ...
        '외부 하중이 작용하는 노드는, 방향 "x"는 0, "y"는 1로 표현해서 loads = [dir load x y] 형식으로 출력해줘. ' ...
        '   예: loads = [0 100 4 3; 1 -200 8 3]; x방향은 오른쪽이 (+)이고 y방향은 위쪽이 (+)이야' ...
        '외부 하중은 숫자가 있다(예 : 10N)면 그 숫자를 쓰고 만약 PN같이 숫자의 크기가 기호라면 1을 써 ' ...
        '형식은 MATLAB 코드 그대로 출력해줘.'
    ]; 



    safePrompt = jsonencode(prompt);
    %jsonBody = sprintf([ ...
        %'{' ...
       % '"model": "opengvlab/internvl3-14b:free",' ...
      % jsonBody = sprintf([ ...
    %'{'...
   % '"model": "gpt-4o",'... % 최신 gpt-4o 사용 추천
   % '"messages": [{' ...
   %     '"role": "user",' ...
    %    '"content": [' ...
     %       '{ "type": "text", "text": %s },' ...
   %         '{ "type": "image_url", "image_url": { "url": %s } }' ...
    %    ']' ...
  %  '}],' ...
  %  '"temperature": 0.5' ... % 
   % '}'], safePrompt, safeImageUrl);

   jsonBody = sprintf([ ...
       '{'...
      '"model": "gpt-4.1",'... %gpt-4.1
        '"messages": [{' ...
            '"role": "user",' ...
            '"content": [' ...
                '{ "type": "text", "text": %s },' ...
                '{ "type": "image_url", "image_url": { "url": %s } }' ...
            ']' ...
        '}]' ...
        '}'], safePrompt, safeImageUrl);


    headers = {
        'Content-Type', 'application/json';
        'Authorization', ['Bearer ' apiKey];
        'HTTP-Referer', 'https://localhost';  
        'X-Title', 'Your Request Title';       
    };

    options = weboptions( ...
        'HeaderFields', headers, ...
        'MediaType', 'application/json', ...
        'Timeout', 90, ...
        'ContentType', 'json' ...
    );

    disp('이미지를 분석중입니다...');


    try
        response = webwrite(apiUrl, jsonBody, options);
        if isfield(response,"choices")
            AItext = response.choices(1).message.content;
            disp('이미지 분석이 성공적으로 완료되었습니다');
        else
            disp('분석에 오류가 발생했습니다');
        end
    catch e
        switch true
            case contains(e.message,'400')
                disp('json에 문제가 생겼을 가능성이 높습니다');
            case contains(e.message,'401')
                disp('APIkey에 문제가 생겼을 가능성이 높습니다');
            case contains(e.message,'429')
                disp('일시적인 오류가 발생했습니다. 잠시 후 다시 시도해 주세요');
            otherwise
                disp('분석을 실패했습니다');
        end
        disp(e.message);
    end

end