function AItext = image2Text(imageFile)

    %apiKey = 
    %apiKey = 
    %apiUrl = 'https://openrouter.ai/api/v1/chat/completions';
    apiUrl = 'https://api.openai.com/v1/chat/completions';

    AItext = ' ';


    %이미지 base64 인코딩
    fid = fopen(imageFile, 'rb');
    imgData = fread(fid, '*uint8');
    fclose(fid);
    imgBase64 = matlab.net.base64encode(imgData);
    safeImageUrl = jsonencode(['data:image/jpeg;base64,' imgBase64]);


prompt = [ ...
    '다음 빔 구조 이미지를 보고, 아래 Beam 명령어 체계에 맞춰서 빔을 구성하려면 어떤 명령어들을 입력해야 하는지 순서대로 작성해 주세요. ' ...
    '\n\n[Beam 명령어 체계]' ...
    '\n  mknod (x,y)                     - 좌표에 노드 생성 (더미 노드)' ...
    '\n  delnod (x,y)                    - 해당 노드 삭제 (포함된 부재도 삭제)' ...
    '\n  mkmem (x1,y1),(x2,y2)           - 두 노드를 연결하여 Beam 부재 생성' ...
    '\n  delmem (x1,y1),(x2,y2)          - 두 노드 사이의 Beam 부재 삭제' ...
    '\n  fix (x,y) fixed|pinned|roller|yroller   - 해당 노드에 지점조건 설정' ...
    '\n  load X|Y (x,y) f                - (x,y) 위치에 집중하중 fx 또는 fy' ...
    '\n  ldist x|y (x1,y1),(x2,y2) f     - 등분포하중 fx 또는 fy' ...
    '\n  ltria x|y (x1,y1),(x2,y2) f     - 삼각형 분포하중 최대값 f' ...
    '\n  moment (x,y) M                  - 위치 (x,y)에 반시계방향 모멘트 M 작용' ...
    '\n\n[출력 형식 규칙]' ...
    '\n1️⃣ 각 명령어는 반드시 한 줄씩만 출력하세요.' ...
    '\n2️⃣ 좌표는 반드시 (x,y) 형식으로 표기하세요.' ...
    '\n3️⃣ 하중값이나 치수에 문자가 포함되어 있으면 최소단위가 1이 되도록 숫자로 변환하세요. 예: ''P''→1, ''2P''→2, ''10kN''→10.' ...
    '\n4️⃣ 출력 순서는 반드시 다음 순서를 지켜야 합니다: ' ...
    '\n   • mknod → mkmem → fix → load/ldist/ltria/moment' ...
    '\n5️⃣ 설명은 절대 쓰지 말고, 명령어만 출력하세요. (예: ''mknod (0,0)'')' ...
    '\n\n위 규칙을 준수하여, 주어진 빔 구조 이미지를 분석하고 필요한 Beam 명령어를 모두 작성해 주세요.' ...
];

    

    safePrompt = jsonencode(prompt);
    %jsonBody = sprintf([ ...
        %'{' ...
       % '"model": "opengvlab/internvl3-14b:free",' ...
       jsonBody = sprintf([ ...
       '{'...
      '"model": "gpt-4.1",'... %gpt-4.1
        '"messages": [{' ...
            '"role": "user",' ...
            '"content": [' ...
                '{ "type": "text", "text": %s },' ...
                '{ "type": "image_url", "image_url": { "url": %s } }' ...
            ']' ...
        '}]' ...
        '}'], safePrompt, safeImageUrl);

    headers = {
        'Content-Type', 'application/json';
        'Authorization', ['Bearer ' apiKey];
        'HTTP-Referer', 'https://localhost';   
        'X-Title', 'Your Request Title';      
    };

    options = weboptions( ...
        'HeaderFields', headers, ...
        'MediaType', 'application/json', ...
        'Timeout', 90, ...
        'ContentType', 'json' ...
    );

    disp('이미지를 분석중입니다...');


    try
        response = webwrite(apiUrl, jsonBody, options);
        if isfield(response,"choices")
            AItext = response.choices(1).message.content;
            disp('이미지 분석이 성공적으로 완료되었습니다');
        else
            disp('분석에 오류가 발생했습니다');
        end
    catch e
        switch true
            case contains(e.message,'400')
                disp('json에 문제가 생겼을 가능성이 높습니다');
            case contains(e.message,'401')
                disp('APIkey에 문제가 생겼을 가능성이 높습니다');
            case contains(e.message,'429')
                disp('일시적인 오류가 발생했습니다. 잠시 후 다시 시도해 주세요');
            otherwise
                disp('분석을 실패했습니다');
        end
        disp(e.message);
    end

end